rssmysql:
  image: mysql:latest
  environment:
    - MYSQL_ROOT_PASSWORD=root
  volumes:
    - /var/lib/javarss/mysql:/var/lib/mysql
  ports:
    - 3307:3306

rssphpmyadmin:
  image: nazarpc/phpmyadmin:latest
  links:
    - rssmysql:mysql
  ports:
    - 4419:80

rssserver:
  build: server/
  links:
    - rssmysql:mysql
  ports:
    - 4422:8080

rssdocapi:
  build: doc/
  ports:
    - 4421:80
