/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import java.awt.GridLayout;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JTextPane;

/**
 *
 * @author Bastien
 */
public class ArticlePreviewView extends javax.swing.JPanel {

    /**
     * Creates new form ArticlePreviewView
     */
    public ArticlePreviewView(String title, String Preview) {
        initComponents();
        this.setLayout(new GridLayout(0, 1));
        this.setBorder(BorderFactory.createLineBorder(Color.yellow));
        TitleLabel.setText(title);
        this.add(TitleLabel);
        PreviewLabel.setContentType("text/html");
        PreviewLabel.setText(Preview);
        this.add(PreviewLabel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        TitleLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PreviewLabel = new javax.swing.JEditorPane();

        setLayout(new java.awt.GridBagLayout());

        TitleLabel.setText("jLabel1");
        add(TitleLabel, new java.awt.GridBagConstraints());

        jScrollPane1.setViewportView(PreviewLabel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(jScrollPane1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane PreviewLabel;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
