/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;

/**
 *
 * @author Bastien
 */
public class LoginView extends javax.swing.JPanel {

    /**
     * Creates new form LoginView
     */
    private OnConnectButtonClick connectEvent;
    
    
    
    
    public LoginView() {
        initComponents();
        this.setBackground(new Color(27, 193, 132));
    }
    
    public static interface OnConnectButtonClick {
        void applyRegister(String login, String pwd);
        void applyLogin(String login, String pwd);
    }
    
    public void setOnConnectButtonClick(OnConnectButtonClick connectEvent) {
        this.connectEvent = connectEvent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        TitleLabel = new javax.swing.JLabel();
        LoginTextField = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();
        ConnectButton = new javax.swing.JButton();
        RegisterButton = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        TitleLabel.setFont(new java.awt.Font("Tahoma", 0, 72)); // NOI18N
        TitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleLabel.setText("Feedify");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(-150, 0, 100, 0);
        add(TitleLabel, gridBagConstraints);

        LoginTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        LoginTextField.setText("login");
        LoginTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 223;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 305, 30, 296);
        add(LoginTextField, gridBagConstraints);

        PasswordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PasswordField.setText("ganjify");
        PasswordField.setOpaque(false);
        PasswordField.setPreferredSize(new java.awt.Dimension(255, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(20, 305, 30, 296);
        add(PasswordField, gridBagConstraints);

        ConnectButton.setText("Connect");
        ConnectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConnectButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(15, 5, 0, 0);
        add(ConnectButton, gridBagConstraints);

        RegisterButton.setText("Register");
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(15, 5, 0, 0);
        add(RegisterButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void LoginTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginTextFieldActionPerformed

    private void ConnectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConnectButtonActionPerformed
       // TODO add your handling code here:
       if (connectEvent != null) {
           connectEvent.applyLogin(LoginTextField.getText(), PasswordField.getText());
       }
    }//GEN-LAST:event_ConnectButtonActionPerformed

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
        // TODO add your handling code here:
        if (connectEvent != null) {
           connectEvent.applyRegister(LoginTextField.getText(), PasswordField.getText());
       }
    }//GEN-LAST:event_RegisterButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConnectButton;
    private javax.swing.JTextField LoginTextField;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JLabel TitleLabel;
    // End of variables declaration//GEN-END:variables
}
